config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users
  

  namespace :admin do
    resources :auth, only: [:login]
    root "index#index"
    get '/login', to: 'auth#login'
    get '/test', to: 'test#index'

    get '/user/edit_password' => 'users#edit_password', as: 'user_edit_password'
    post '/user/update_password' => 'users#update_password', as: 'user_update_password'

    resources :articles
    post '/articles/upload_image' => 'articles#upload_image', as: 'articles_upload_image'
    resources :categories
  end

  root "articles#index"
  get '/categories/:id', to: 'articles#category', as: 'category'
  get '/articles/:id', to: 'articles#show', as: 'article'
  get 'rss', to: 'articles#feed'
  get 'feed', to: 'articles#feed'
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable, :timeoutable, :lockable, :timeout_in => 8.hours
  validates_format_of :email,:with => Devise.email_regexp
  # validates :email, :presence => true, :email => true
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :category

  validates :title, presence: true
  validates :content, presence: true

  scope :resent, -> {order(created_at: :desc)}
end

app/models/article_attachment.rb
class ArticleAttachment < ActiveRecord::Base
  belongs_to :article
  belongs_to :attachment
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  mount_uploader :file, AttachmentUploader
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :articles
  validates :name, presence: true
end

app/models/draft.rb
class Draft < ActiveRecord::Base
  belongs_to :article
  belongs_to :category
end

app/controllers/admin/articles_controller.rb
# -*- coding: utf-8 -*-
class Admin::ArticlesController < Admin::BaseController
  skip_before_filter :verify_authenticity_token, :only => :upload_image

  def index
    @articles = Article.resent.paginate(:page => params[:page], :per_page => 30)
  end

  def new
    @article = Article.new
    @article.summary_length = 280
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)
    @article.save
    redirect_to admin_articles_path
    # render plain: params[:article].inspect
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)
    redirect_to admin_articles_path
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to admin_articles_path
  end

  def upload_image
    image = Attachment.new({:file => params[:imgFile]})
    has_one = Attachment.where(:file => image.file.filename).first
    if has_one.present?
      path = has_one.file.url
    else
      image.save
      path = image.file.url
    end

    if path
      render json: {error: 0, url: path}
    else
      render json: {error: 1, message: "upload error"}
    end
  end

  def article_params
    params.require(:article).permit(:title, :category_id, :content, :summary_length)
  end
end

app/controllers/admin/auth_controller.rb
class Admin::AuthController < Admin::BaseController
  skip_before_action :authenticate_admin_user!
  def login
    render "admin/auth/login", :layout => false
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  layout 'admin/application'
  before_action :authenticate_admin_user!
end

app/controllers/admin/categories_controller.rb
# -*- coding: utf-8 -*-
class Admin::CategoriesController < Admin::BaseController

  def index
    @categories = Category.order('position asc').all
  end

  def new
    @category = Category.new
  end

  def edit
    @category = Category.find(params[:id])
  end

  def create
    @category = Category.new(category_params)
    @category.save
    redirect_to admin_categories_path
  end

  def update
    @category = Category.find(params[:id])
    @category.update(category_params)
    redirect_to admin_categories_path
  end

  def destroy
    @category = Category.find(params[:id])
    if @category.articles.count > 0
      redirect_to admin_categories_path, alert: "此分类下还有文章，不能删除"
    else
      @category.destroy
      redirect_to admin_categories_path
    end
  end

  def category_params
    params.require(:category).permit(:name, :position)
  end
end

app/controllers/admin/index_controller.rb
class Admin::IndexController < Admin::BaseController
  def index
    render "admin/index", :layout => false
  end
end

app/controllers/admin/test_controller.rb
class Admin::TestController < Admin::BaseController
  def index
    render 'admin/test'
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_filter :authenticate_admin_user!
  
  def edit_password
  end

  def update_password
    @user = AdminUser.find(current_admin_user.id)
    if @user.update(params.permit(:password))
      # Sign in the user by passing validation in case their password changed
      # sign_in @user, :bypass => true
      redirect_to admin_root_path
    else
      render "edit"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout :layout

  private

  def layout
    # only turn it off for login pages:
    is_a?(Devise::SessionsController) ? false : "application"
    # or turn layout off for every devise controller:
    # devise_controller? && "application"
  end
end

app/controllers/articles_controller.rb
# -*- coding: utf-8 -*-
class ArticlesController < BaseController

  before_action :fetch_categories

  def fetch_categories
    @categories = Category.order('position asc').all    
  end
  
  def index
    @articles = Article.resent.paginate(:page => params[:page], :per_page => 12)
  end

  def feed
    @articles = Article.resent.limit(20)
    render :template => 'articles/feed.rss.builder', :layout => false
    # respond_to do |format|
    #  format.rss { render :layout => false }
    # end
  end

  def category
    @category = Category.find(params[:id])
    if @category
      @articles = Article.resent.where(category_id: @category.id).paginate(:page => params[:page], :per_page => 12)
      render 'articles/index'
    else
      redirect_to root_path, alert: '分类不存在'
    end
  end

  def show
    @article = Article.find(params[:id])
  end

end

app/controllers/base_controller.rb
class BaseController < ApplicationController
end

app/helpers/admin/article_helper.rb
module Admin::ArticleHelper
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
# -*- coding: utf-8 -*-
module ApplicationHelper
  def plaintext_summary(text, length: 280)
    doc = Nokogiri::HTML::DocumentFragment.parse(text)
    simple_format(truncate(doc.css('p').map(&:text).join('').to_s, :length => length))
  end

  def current_category(category = nil, current_id = 0)
    ' class="current"' if (category.nil? and current_id == 0) or (category and category.id == current_id)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  # A simple way to show error messages for the current devise resource. If you need
  # to customize this method, you can either overwrite it in your application helpers or
  # copy the views to your application.
  #
  # This method is intended to stay simple and it is unlikely that we are going to change
  # it to add more behavior or options.
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      count: resource.errors.count,
                      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div id="error_explanation">
      <h2>#{sentence}</h2>
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end
end

app/views/admin/article/_form.html.erb
<%= form_for @article, url: admin_article_path, html:{class:"definewidth m20"} do |f| %>
    <table class="table table-bordered table-hover definewidth m10">
      <tr>
        <td width="10%" class="tableleft">标题</td>
        <td>
          <%= f.text_field :title %>
        </td>
      </tr>
      <tr>
        <td class="tableleft">内容</td>
        <td>
          <%= f.text_area :content %>
        </td>
      </tr>
      <tr>
        <td class="tableleft"></td>
        <td>
          <%= f.submit "保存", :class => "btn btn-primary" %>&nbsp;&nbsp;
          <%= f.button "返回列表", :class => "btn btn-success", :id => "backid" %>
        </td>
      </tr>
    </table>
<% end %>

app/views/admin/article/index.html.erb
<%= form_tag admin_article_index_path, class:"form-inline definewidth m20", method:"get" do %>
  关键字：
    <%= text_field_tag :keywords, nil, :class => "abc input-default" %>&nbsp;&nbsp;
    <%= submit_tag "查询", :class => "btn btn-primary" %>&nbsp;&nbsp;
    <%= button_tag "新增文章", :type => "button", :class => "btn btn-success", :id => "addnew" %>
<% end %>

<table class="table table-bordered table-hover definewidth m10">
  <thead>
  <tr>
    <th>ID</th>
    <th>标题</th>
    <th>创建时间</th>
    <th>修改时间</th>
    <th>操作</th>
  </tr>
  </thead>
  <% @articles.each do |article| %>
  <tr>
    <td><%= article.id %></td>
    <td><%= article.title %>></td>
    <td><%= article.created_at %>></td>
    <td><%= article.updated_at %></td>
    <td>
      <a href="edit.html">编辑</a>
    </td>
  </tr>
  <% end %>
</table>

<div>
  <%= will_paginate @articles %>
</div>

<script>

  $(function(){
      $("#addnew").click(function(){
          location.href = "<%= new_admin_article_path %>";
      });
  });

    function del(id)
    {

        if(confirm("确定要删除吗？"))
        {
            var url = "index.html";
            window.location.href=url;
        }

    }
</script>

app/views/admin/articles/_form.html.erb
<%= form_for [:admin, @article], html:{class:"definewidth m20"} do |f| %>
    <table class="table table-bordered table-hover definewidth m10">
      <tr>
        <td width="10%" class="tableleft">标题</td>
        <td>
          <%= f.text_field :title, :style => 'width:80%;' %>
        </td>
      </tr>
      <tr>
        <td width="10%" class="tableleft">分类</td>
        <td>
          <%= f.collection_select :category_id, Category.order('position asc').all, :id, :name %>
        </td>
      </tr>
      <tr>
        <td width="10%" class="tableleft">摘要长度</td>
        <td>
          <%= f.text_field :summary_length %>（0表示全部显示）
        </td>
      </tr>      
      <tr>
        <td class="tableleft">内容</td>
        <td>
          <%= f.text_area :content, :style => "width: 600px; height: 300px;" %>
        </td>
      </tr>
      <tr>
        <td class="tableleft"></td>
        <td>
          <%= f.submit "发布", :class => "btn btn-primary" %>&nbsp;&nbsp;
          <%= f.button "返回列表", :class => "btn btn-success", :id => "backid" %>
        </td>
      </tr>
    </table>
<% end %>


<script charset="utf-8" src="<%= root_path + 'kindeditor/kindeditor-min.js' %>"></script>
<script charset="utf-8" src="<%= root_path + 'kindeditor/lang/zh_CN.js' %>"></script>
<script>
    KindEditor.ready(function(K) {
        window.editor = K.create('#article_content', {
            cssPath : ['<%= stylesheet_path "prettify" %>', '<%= stylesheet_path "kindeditor" %>'],
            width: "700px",
            height: "420px",
            uploadJson: "<%= admin_articles_upload_image_path %>"
        });
    });
</script>

app/views/admin/articles/edit.html.erb
<%= render "admin/articles/form" %>

app/views/admin/articles/index.html.erb
<%= form_tag admin_articles_path, class:"form-inline definewidth m20", method:"get" do %>
  关键字：
    <%= text_field_tag :keywords, nil, :class => "abc input-default" %>&nbsp;&nbsp;
    <%= submit_tag "查询", :class => "btn btn-primary" %>&nbsp;&nbsp;
    <%= button_tag "新增文章", :type => "button", :class => "btn btn-success", :id => "addnew" %>
<% end %>

<table class="table table-bordered table-hover definewidth m10">
  <thead>
  <tr>
    <th>ID</th>
    <th>标题</th>
    <th>分类</th>
    <th>创建时间</th>
    <th>修改时间</th>
    <th>操作</th>
  </tr>
  </thead>
  <% @articles.each do |article| %>
  <tr>
    <td><%= article.id %></td>
    <td><%= article.title %></td>
    <td><%= article.category.name %></td>
    <td><%= article.created_at.localtime.strftime "%Y-%m-%d %H:%M:%S" %></td>
    <td><%= article.updated_at.localtime.strftime "%Y-%m-%d %H:%M:%S" %></td>
    <td>
      <%= link_to "编辑", edit_admin_article_path(article) %>
      <%= link_to "删除", admin_article_path(article), method: 'delete', data:{confirm: "确定要删除这篇文章吗？"} %>
    </td>
  </tr>
  <% end %>
</table>

<div>
  <%= will_paginate @articles %>
</div>

<script>

  $(function(){
      $("#addnew").click(function(){
          location.href = "<%= new_admin_article_path %>";
      });
  });

    function del(id)
    {

        if(confirm("确定要删除吗？"))
        {
            var url = "index.html";
            window.location.href=url;
        }

    }
</script>

app/views/admin/articles/new.html.erb
<%= render "admin/articles/form" %>

app/views/admin/categories/_form.html.erb
<%= form_for [:admin, @category], html:{class:"definewidth m20"} do |f| %>
    <table class="table table-bordered table-hover definewidth m10">
      <tr>
        <td width="10%" class="tableleft">名称</td>
        <td>
          <%= f.text_field :name %>
        </td>
      </tr>
      <tr>
        <td width="10%" class="tableleft">位置</td>
        <td>
          <%= f.text_field :position %>
        </td>
      </tr>
      <tr>
        <td class="tableleft"></td>
        <td>
          <%= f.submit "保存", :class => "btn btn-primary" %>&nbsp;&nbsp;
          <%= f.button "返回列表", :class => "btn btn-success", :id => "backid" %>
        </td>
      </tr>
    </table>
<% end %>

app/views/admin/categories/edit.html.erb
<%= render "admin/categories/form" %>

app/views/admin/categories/index.html.erb
<div style="margin:10px 20px;">
<%= button_tag "新增分类", :type => "button", :class => "btn btn-success", :id => "addnew" %>
</div>

<table class="table table-bordered table-hover definewidth m10">
  <thead>
  <tr>
    <th>ID</th>
    <th>名称</th>
    <th>位置</th>
    <th>创建时间</th>
    <th>修改时间</th>
    <th>操作</th>
  </tr>
  </thead>
  <% @categories.each do |category| %>
  <tr>
    <td><%= category.id %></td>
    <td><%= category.name %></td>
    <td><%= category.position %></td>
    <td><%= category.created_at.localtime.strftime "%Y-%m-%d %H:%M:%S" %></td>
    <td><%= category.updated_at.localtime.strftime "%Y-%m-%d %H:%M:%S" %></td>
    <td>
      <%= link_to "编辑", edit_admin_category_path(category) %>
      <%= link_to "删除", admin_category_path(category), method: 'delete', data:{confirm: "确定要删除这个分类吗？"} %>
    </td>
  </tr>
  <% end %>
</table>

<script>

  $(function(){
      $("#addnew").click(function(){
          location.href = "<%= new_admin_category_path %>";
      });
  });

</script>

app/views/admin/categories/new.html.erb
<%= render "admin/categories/form" %>

app/views/articles/index.html.erb
<% content_for :meta do%>
<% if defined? @category%>
<title><%= @category.name %> - FREDYANG的博客</title>
<meta name="keywords" content="<%= @category.name %> - FREDYANG的博客">
<meta name="description" content="关于<%= @category.name %>的文章">
<% else %>
<title>FREDYANG的博客</title>
<meta name="keywords" content="FREDYANG的博客">
<meta name="description" content="关于互联网、产品、开发和相关思想的记录">
<% end %>
<% end %>

<% @articles.each do |article| %>
<div class="blog-post">
  <h2 class="blog-post-title">
    <%= link_to article.title, article_path(article) %>
  </h2>

  <p>
    <% if article.summary_length > 0 %>
      <%= plaintext_summary article.content, :length => article.summary_length %>
    <% else %>
      <%= article.content.html_safe %>
    <% end %>
  </p>

  <p class="blog-post-meta"><%= article.created_at.localtime.strftime "%Y-%m-%d" %></p>

</div>
<% end %>

<% if @articles.total_pages > 1 %>
<nav>
  <ul class="pager">
    <% if @articles.previous_page %>
    <li>
      <%= link_to "< Previous Page", params.merge(:page => @articles.previous_page) %>
    </li>
    <% end %>

    <% if @articles.next_page %>
    <li>
      <%= link_to "Next Page >", params.merge(:page => @articles.next_page) %>
    </li>
    <% end %>
  </ul>
</nav>
<% end %>

app/views/articles/show.html.erb
<% content_for :meta do%>
<title><%= @article.title %> - FREDYANG的博客</title>
<meta name="keywords" content="<%= @article.title %>">
<meta name="description" content="<%= sanitize(@article.content.gsub(/["']/, ''), :tags => []).squish.truncate(80, :omission => '') %>">
<% end %>


<h2 class="blog-post-title">
  <%= @article.title %>
</h2>
<p class="blog-post-meta"><%= @article.created_at.localtime.strftime "%Y-%m-%d" %></p>

<p>
  <%= @article.content.html_safe %>
</p>