config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users
  

  namespace :admin do
    resources :auth, only: [:login]
    root "index#index"
    get '/login', to: 'auth#login'
    get '/test', to: 'test#index'

    get '/user/edit_password' => 'users#edit_password', as: 'user_edit_password'
    post '/user/update_password' => 'users#update_password', as: 'user_update_password'

    resources :articles
    post '/articles/upload_image' => 'articles#upload_image', as: 'articles_upload_image'
    resources :categories
  end

  root "articles#index"
  get '/categories/:id', to: 'articles#category', as: 'category'
  get '/articles/:id', to: 'articles#show', as: 'article'
  get 'rss', to: 'articles#feed'
  get 'feed', to: 'articles#feed'
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable, :timeoutable, :lockable, :timeout_in => 8.hours
  validates_format_of :email,:with => Devise.email_regexp
  # validates :email, :presence => true, :email => true
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :category

  validates :title, presence: true
  validates :content, presence: true

  scope :resent, -> {order(created_at: :desc)}
end

app/models/article_attachment.rb
class ArticleAttachment < ActiveRecord::Base
  belongs_to :article
  belongs_to :attachment
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  mount_uploader :file, AttachmentUploader
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :articles
  validates :name, presence: true
end

app/models/draft.rb
class Draft < ActiveRecord::Base
  belongs_to :article
  belongs_to :category
end

app/controllers/admin/auth_controller.rb
class Admin::AuthController < Admin::BaseController
  skip_before_action :authenticate_admin_user!
  def login
    render "admin/auth/login", :layout => false
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  layout 'admin/application'
  before_action :authenticate_admin_user!
end

app/controllers/admin/index_controller.rb
class Admin::IndexController < Admin::BaseController
  def index
    render "admin/index", :layout => false
  end
end

app/controllers/admin/test_controller.rb
class Admin::TestController < Admin::BaseController
  def index
    render 'admin/test'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout :layout

  private

  def layout
    # only turn it off for login pages:
    is_a?(Devise::SessionsController) ? false : "application"
    # or turn layout off for every devise controller:
    # devise_controller? && "application"
  end
end

app/controllers/articles_controller.rb
# -*- coding: utf-8 -*-
class ArticlesController < BaseController

  before_action :fetch_categories

  def fetch_categories
    @categories = Category.order('position asc').all    
  end
  
  def index
    @articles = Article.resent.paginate(:page => params[:page], :per_page => 12)
  end

  def feed
    @articles = Article.resent.limit(20)
    render :template => 'articles/feed.rss.builder', :layout => false
    # respond_to do |format|
    #  format.rss { render :layout => false }
    # end
  end

  def category
    @category = Category.find(params[:id])
    if @category
      @articles = Article.resent.where(category_id: @category.id).paginate(:page => params[:page], :per_page => 12)
      render 'articles/index'
    else
      redirect_to root_path, alert: '分类不存在'
    end
  end

  def show
    @article = Article.find(params[:id])
  end

end

app/controllers/base_controller.rb
class BaseController < ApplicationController
end

app/helpers/admin/article_helper.rb
module Admin::ArticleHelper
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
# -*- coding: utf-8 -*-
module ApplicationHelper
  def plaintext_summary(text, length: 280)
    doc = Nokogiri::HTML::DocumentFragment.parse(text)
    simple_format(truncate(doc.css('p').map(&:text).join('').to_s, :length => length))
  end

  def current_category(category = nil, current_id = 0)
    ' class="current"' if (category.nil? and current_id == 0) or (category and category.id == current_id)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  # A simple way to show error messages for the current devise resource. If you need
  # to customize this method, you can either overwrite it in your application helpers or
  # copy the views to your application.
  #
  # This method is intended to stay simple and it is unlikely that we are going to change
  # it to add more behavior or options.
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      count: resource.errors.count,
                      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div id="error_explanation">
      <h2>#{sentence}</h2>
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end
end

app/views/admin/index.html.erb
<!DOCTYPE HTML>
<html>
<head>
  <title>后台管理系统</title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <%= stylesheet_link_tag "admin/dpl-min" %>
  <%= stylesheet_link_tag "admin/bui-min" %>
  <%= stylesheet_link_tag "admin/main-min" %>
</head>
<body>

<div class="header">

  <div class="dl-title">
    <!--<img src="/chinapost/Public/assets/img/top.png">-->
  </div>

  <div class="dl-log">
    欢迎您，<span class="dl-log-user"><%=current_admin_user.email%></span>
    <%= link_to('[退出]', destroy_admin_user_session_path, :method => :delete, :class => "dl-log-quit") %>
  </div>
</div>
<div class="content">
  <div class="dl-main-nav">
    <div class="dl-inform">
      <div class="dl-inform-title"><s class="dl-inform-icon dl-up"></s></div>
    </div>
    <ul id="J_Nav" class="nav-list ks-clear">
      <li class="nav-item dl-selected">
        <div class="nav-item-inner nav-home">文章管理</div>
      </li>
      <li class="nav-item dl-selected">
        <div class="nav-item-inner nav-order">系统管理</div>
      </li>

    </ul>
  </div>
  <ul id="J_NavContent" class="dl-tab-conten">

  </ul>
</div>
<%= javascript_include_tag "admin/jquery-1.8.1.min" %>
<%= javascript_include_tag "admin/bui-min" %>
<%= javascript_include_tag "admin/common/main-min" %>
<%= javascript_include_tag "admin/config-min" %>
<script>
    BUI.use('common/main', function () {
        var config = [
            {
                id: '1',
                homePage: '11',
                menu: [{
                    text: '文章管理',
                    items: [
                        {id: '11', text: '文章列表', href: '<%= admin_articles_path %>'},
                        {id: '12', text: '文章分类', href: '<%= admin_categories_path %>'}
                    ]
                }]
            },
            {
                id: '2',
                homePage: '21',
                menu: [
                    {
                        text: '系统管理',
                        items: [
                            {id: '21', text: '修改密码', href: '<%= admin_user_edit_password_path %>'}
                        ]
                    }
                ]
            }
        ];
        new PageUtil.MainPage({
            modulesConfig: config
        });
    });
</script>
</body>
</html>

app/views/admin/test.html.erb
<%= stylesheet_link_tag "admin/bui-min" %>

hello

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
  <meta charset="UTF-8">
  <%= stylesheet_link_tag "admin/bootstrap.min" %>
  <%= stylesheet_link_tag "admin/bootstrap-responsive" %>
  <%= stylesheet_link_tag "admin/style" %>

  <%= javascript_include_tag "admin/jquery" %>
  <%= javascript_include_tag "admin" %>
  <%= javascript_include_tag "admin/bootstrap" %>
  <%= javascript_include_tag "admin/ckform" %>
  <%= javascript_include_tag "admin/common" %>

  <%= csrf_meta_tag %>

  <style type="text/css">
      body {
          padding-bottom: 40px;
      }
      .sidebar-nav {
          padding: 9px 0;
      }
      @media (max-width: 980px) {
          /* Enable use of floated navbar text */
          .navbar-text.pull-right {
              float: none;
              padding-left: 5px;
              padding-right: 5px;
          }
      }
  </style>
</head>
<body>
<%= yield %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= yield :meta %>
    <link rel="icon" href="favicon.ico">

    <link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.1/css/bootstrap.min.css">
    <%= stylesheet_link_tag "blog" %>
    <%= stylesheet_link_tag "prettify" %>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="http://cdn.bootcss.com/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="http://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <%= auto_discovery_link_tag(:rss, "http://www.fredyang.com/rss") %>
  </head>

  <body onload="prettyPrint()">

    <div class="blog-masthead">
      <div class="container blog-name">
          <a href="<%= root_path %>" style="color:#FFF; text-decoration:none;">FREDYANG</a>
      </div>
    </div>

    <div class="container">

      <div class="row">

        <div class="col-sm-8 blog-main">

	  <%= yield %>

        </div><!-- /.blog-main -->

        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
          <div class="sidebar-module sidebar-module-inset">
            <h4>Categories</h4>
            <ol class="list-unstyled">
              <li<%= sanitize current_category(@category) %>><%= link_to "全部", root_path%></li>
	      <% @categories.each do |category| %>
	      <li<%= sanitize current_category(@category, category.id) %>><%= link_to category.name, category_path(category) %></li>
	      <% end %>
            </ol>
          </div>
          <div class="sidebar-module sidebar-module-inset">
            <h4>About</h4>
            <p>
	       <div style="margin-bottom:6px;">FREDYANG，项目经理、产品经理、PHP工程师、Ruby工程师，热爱开发，热爱互联网；<br />Email: shuky2000#163.com<br /><br />此博客使用Ruby on Rails开发，从前台到后台，从开发到部署，麻雀虽小五脏俱全，开源地址：<a href="http://git.io/AzK7" target="_blank">http://git.io/AzK7</a></div>
	       <ul>
		 <li>Framework：Ruby on Rails</li>
		 <li>Frontend：Bootstrap</li>
		 <li>Repository: github</li>
		 <li>IDE: Emacs</li>
		 <li>ENV: Centos6 + Nginx</li>
	       </ul>
	    </p>
          </div>	  
<!--
          <div class="sidebar-module">
            <h4>Elsewhere</h4>
            <ol class="list-unstyled">
              <li><a href="#">GitHub</a></li>
              <li><a href="#">Twitter</a></li>
              <li><a href="#">Facebook</a></li>
            </ol>
          </div>
-->
        </div><!-- /.blog-sidebar -->

      </div><!-- /.row -->

    </div><!-- /.container -->

    <div class="blog-footer">
      <p>
        <a href="#">Back to top</a>
      </p>      
      <p>京ICP备13047626号-4 &copy; 2015 Fredyang</p>
    </div>

<!--
    <script src="http://cdn.bootcss.com/jquery/2.1.3/jquery.min.js"></script>
    <script src="http://cdn.bootcss.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
-->
    <%= javascript_include_tag "prettify" %>

    <script>
      var _hmt = _hmt || [];
      (function() {
      var hm = document.createElement("script");
      hm.src = "//hm.baidu.com/hm.js?876144c155620cf3517ab0681e6f8022";
      var s = document.getElementsByTagName("script")[0]; 
      s.parentNode.insertBefore(hm, s);
      })();
    </script>
    
  </body>
</html>